import React, { useEffect, useRef, useState } from 'react';
import { Pressable, View } from 'react-native';
import { colors, spacing } from '../../theme';
import { PixelText } from '../../components/PixelText';
import { type GameApi } from '../engine/GameShell';
import { playSfx } from '../../audio/sfx';
import { haptic } from '../../haptics';

/**
 * Lights-Out mechanics: tapping a lamp toggles it and its four neighbors;
 * darken the whole 5×5 board. Puzzles are generated by tapping random cells
 * on a dark board, so every one is solvable. Three rounds per game with more
 * scrambles each round; fewer taps = more points. Pure deduction, no clock.
 */
const N = 5;
const ROUNDS = 3;

export function NeonLightsGame({ api }: { api: GameApi }) {
  const [lights, setLights] = useState<boolean[]>([]);
  const [round, setRound] = useState(1);
  const [taps, setTaps] = useState(0);
  const score = useRef(0);

  const toggleAt = (b: boolean[], idx: number) => {
    const x = idx % N;
    const y = Math.floor(idx / N);
    b[idx] = !b[idx];
    if (x > 0) b[idx - 1] = !b[idx - 1];
    if (x < N - 1) b[idx + 1] = !b[idx + 1];
    if (y > 0) b[idx - N] = !b[idx - N];
    if (y < N - 1) b[idx + N] = !b[idx + N];
  };

  const scramble = (r: number): boolean[] => {
    const b = Array(N * N).fill(false);
    const seeds = 3 + r * 2; // rounds get deeper
    const used = new Set<number>();
    while (used.size < seeds) used.add(Math.floor(Math.random() * N * N));
    used.forEach((i) => toggleAt(b, i));
    return b;
  };

  const startRound = (r: number) => {
    setRound(r);
    setTaps(0);
    setLights(scramble(r));
  };

  useEffect(() => {
    score.current = 0;
    api.setScore(0);
    startRound(1);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [api.resetToken]);

  const tap = (idx: number) => {
    if (!api.running) return;
    setLights((prev) => {
      const b = [...prev];
      toggleAt(b, idx);
      playSfx('flip');
      haptic.light();
      const t = taps + 1;
      setTaps(t);

      if (b.every((v) => !v)) {
        const seeds = 3 + round * 2;
        const gained = Math.max(50, 300 - Math.max(0, t - seeds) * 15);
        score.current += gained;
        api.setScore(score.current);
        playSfx('match');
        haptic.medium();
        if (round >= ROUNDS) {
          api.end({ score: score.current, won: true });
        } else {
          setTimeout(() => startRound(round + 1), 700);
        }
      }
      return b;
    });
  };

  const size = Math.floor(Math.min(api.width - spacing.l * 2, api.height - 100) / N);

  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <PixelText size="label" color={colors.textDim} style={{ marginBottom: spacing.m }}>
        {`${round}/${ROUNDS} · ▲ ${taps}`}
      </PixelText>
      <View style={{ width: size * N }}>
        <View style={{ flexDirection: 'row', flexWrap: 'wrap' }}>
          {lights.map((on, i) => (
            <Pressable
              key={i}
              accessibilityRole="button"
              onPressIn={() => tap(i)}
              style={{
                width: size - 6,
                height: size - 6,
                margin: 3,
                borderRadius: 6,
                backgroundColor: on ? colors.neonYellow : colors.bgCard,
                borderWidth: 2,
                borderColor: on ? colors.neonYellow : colors.border,
                shadowColor: on ? colors.neonYellow : undefined,
                shadowOpacity: on ? 0.9 : 0,
                shadowRadius: 8,
              }}
            />
          ))}
        </View>
      </View>
    </View>
  );
}
