import React from 'react';
import type { ImageSourcePropType } from 'react-native';
import { categoryColors } from '../theme';
import { type GameApi } from './engine/GameShell';
import { SnakeGame } from './snake/SnakeGame';
import { BrickBreakerGame } from './brickbreaker/BrickBreakerGame';
import { PaddleDuelGame } from './paddleduel/PaddleDuelGame';
import { SpaceDefendersGame } from './spacedefenders/SpaceDefendersGame';
import { MemoryMatchGame } from './memorymatch/MemoryMatchGame';
import { NeonStackGame } from './neonstack/NeonStackGame';
import { SolitaireGame } from './solitaire/SolitaireGame';
import { RoadHopperGame } from './roadhopper/RoadHopperGame';
import { PixelWingsGame } from './pixelwings/PixelWingsGame';
import { TileFusionGame } from './tilefusion/TileFusionGame';
import { RetroRacerGame } from './retroracer/RetroRacerGame';
import { DiveSquadronGame } from './divesquadron/DiveSquadronGame';
import { EggCatchGame } from './eggcatch/EggCatchGame';
import { AlleyBowlGame } from './alleybowl/AlleyBowlGame';

import { TankBattleGame } from './tankbattle/TankBattleGame';
import { TowerClimbGame } from './towerclimb/TowerClimbGame';
import { JungleDashGame } from './jungledash/JungleDashGame';
import { BlastMazeGame } from './blastmaze/BlastMazeGame';
import { ChopperRescueGame } from './chopperrescue/ChopperRescueGame';
import { CratePushGame } from './cratepush/CratePushGame';
import { PixelLogicGame } from './pixellogic/PixelLogicGame';
import { FourStackGame } from './fourstack/FourStackGame';

import { FruitSliceGame } from './fruitslice/FruitSliceGame';
import { SkyJumpGame } from './skyjump/SkyJumpGame';
import { BlockDropGame } from './blockdrop/BlockDropGame';
import { BinShotGame } from './binshot/BinShotGame';
import { PaperGliderGame } from './paperglider/PaperGliderGame';
import { DotsBoxesGame } from './dotsboxes/DotsBoxesGame';
import { EraserFlickGame } from './eraserflick/EraserFlickGame';
import { MathSprintGame } from './mathsprint/MathSprintGame';
import { PinballGame } from './pinball/PinballGame';
import { BubblePopGame } from './bubblepop/BubblePopGame';
import { AirHockeyGame } from './airhockey/AirHockeyGame';
import { ClawMachineGame } from './clawmachine/ClawMachineGame';
import { PoolBallGame } from './poolball/PoolBallGame';

export type Category = 'classics' | 'action' | 'arcade' | 'school' | 'brain';

export interface GameDef {
  id: string;
  category: Category;
  /** Demo tier: Snake + Memory Match are free; everything else needs the unlock. */
  free: boolean;
  /** Games with a lives counter in the header. */
  showLives?: boolean;
  /** Emoji glyph, kept for compact contexts (notifications, docs). */
  icon: string;
  /** Original pixel-art card sprite (generated by scripts/gen-game-icons.mjs). */
  art: ImageSourcePropType;
  render: (api: GameApi) => React.ReactNode;
}

/** Sprite per game — regenerate with `node scripts/gen-game-icons.mjs`. */
const ART: Record<string, ImageSourcePropType> = {
  snake: require('../../assets/games/snake.png'),
  brickbreaker: require('../../assets/games/brickbreaker.png'),
  paddleduel: require('../../assets/games/paddleduel.png'),
  neonstack: require('../../assets/games/neonstack.png'),
  solitaire: require('../../assets/games/solitaire.png'),
  roadhopper: require('../../assets/games/roadhopper.png'),
  retroracer: require('../../assets/games/retroracer.png'),
  eggcatch: require('../../assets/games/eggcatch.png'),
  spacedefenders: require('../../assets/games/spacedefenders.png'),
  pixelwings: require('../../assets/games/pixelwings.png'),
  divesquadron: require('../../assets/games/divesquadron.png'),
  memorymatch: require('../../assets/games/memorymatch.png'),
  tilefusion: require('../../assets/games/tilefusion.png'),
  alleybowl: require('../../assets/games/alleybowl.png'),
  tankbattle: require('../../assets/games/tankbattle.png'),
  towerclimb: require('../../assets/games/towerclimb.png'),
  jungledash: require('../../assets/games/jungledash.png'),
  blastmaze: require('../../assets/games/blastmaze.png'),
  chopperrescue: require('../../assets/games/chopperrescue.png'),
  cratepush: require('../../assets/games/cratepush.png'),
  pixellogic: require('../../assets/games/pixellogic.png'),
  fourstack: require('../../assets/games/fourstack.png'),
  fruitslice: require('../../assets/games/fruitslice.png'),
  skyjump: require('../../assets/games/skyjump.png'),
  blockdrop: require('../../assets/games/blockdrop.png'),
  binshot: require('../../assets/games/binshot.png'),
  paperglider: require('../../assets/games/paperglider.png'),
  dotsboxes: require('../../assets/games/dotsboxes.png'),
  eraserflick: require('../../assets/games/eraserflick.png'),
  mathsprint: require('../../assets/games/mathsprint.png'),
  pinball: require('../../assets/games/pinball.png'),
  bubblepop: require('../../assets/games/bubblepop.png'),
  airhockey: require('../../assets/games/airhockey.png'),
  clawmachine: require('../../assets/games/clawmachine.png'),
  poolball: require('../../assets/games/poolball.png'),
};

const DEFS: Omit<GameDef, 'art'>[] = [
  // Classics
  { id: 'snake', category: 'classics', free: true, icon: '🐍', render: (api) => <SnakeGame api={api} /> },
  { id: 'brickbreaker', category: 'classics', free: false, showLives: true, icon: '🧱', render: (api) => <BrickBreakerGame api={api} /> },
  { id: 'paddleduel', category: 'classics', free: false, icon: '🏓', render: (api) => <PaddleDuelGame api={api} /> },
  { id: 'neonstack', category: 'classics', free: false, icon: '🟦', render: (api) => <NeonStackGame api={api} /> },
  { id: 'solitaire', category: 'classics', free: false, icon: '♠️', render: (api) => <SolitaireGame api={api} /> },
  { id: 'roadhopper', category: 'classics', free: false, showLives: true, icon: '🐸', render: (api) => <RoadHopperGame api={api} /> },
  { id: 'retroracer', category: 'classics', free: false, icon: '🏎️', render: (api) => <RetroRacerGame api={api} /> },
  { id: 'tankbattle', category: 'classics', free: false, showLives: true, icon: '🪖', render: (api) => <TankBattleGame api={api} /> },
  { id: 'eggcatch', category: 'classics', free: false, showLives: true, icon: '🥚', render: (api) => <EggCatchGame api={api} /> },
  { id: 'alleybowl', category: 'classics', free: false, icon: '🎳', render: (api) => <AlleyBowlGame api={api} /> },
  // Action
  { id: 'spacedefenders', category: 'action', free: false, showLives: true, icon: '👾', render: (api) => <SpaceDefendersGame api={api} /> },
  { id: 'fruitslice', category: 'action', free: false, showLives: true, icon: '🍉', render: (api) => <FruitSliceGame api={api} /> },
  { id: 'towerclimb', category: 'action', free: false, showLives: true, icon: '🦍', render: (api) => <TowerClimbGame api={api} /> },
  { id: 'pixelwings', category: 'action', free: false, icon: '🐦', render: (api) => <PixelWingsGame api={api} /> },
  { id: 'jungledash', category: 'action', free: false, icon: '🌴', render: (api) => <JungleDashGame api={api} /> },
  { id: 'blastmaze', category: 'action', free: false, showLives: true, icon: '💣', render: (api) => <BlastMazeGame api={api} /> },
  { id: 'divesquadron', category: 'action', free: false, showLives: true, icon: '🛸', render: (api) => <DiveSquadronGame api={api} /> },
  { id: 'chopperrescue', category: 'action', free: false, showLives: true, icon: '🚁', render: (api) => <ChopperRescueGame api={api} /> },
  { id: 'skyjump', category: 'action', free: false, icon: '🦘', render: (api) => <SkyJumpGame api={api} /> },
  // Arcade Corner
  { id: 'pinball', category: 'arcade', free: false, showLives: true, icon: '🪩', render: (api) => <PinballGame api={api} /> },
  { id: 'bubblepop', category: 'arcade', free: false, icon: '🫧', render: (api) => <BubblePopGame api={api} /> },
  { id: 'poolball', category: 'arcade', free: false, showLives: true, icon: '🎱', render: (api) => <PoolBallGame api={api} /> },
  { id: 'clawmachine', category: 'arcade', free: false, showLives: true, icon: '🧸', render: (api) => <ClawMachineGame api={api} /> },
  { id: 'airhockey', category: 'arcade', free: false, icon: '🏒', render: (api) => <AirHockeyGame api={api} /> },
  // School Days
  { id: 'binshot', category: 'school', free: false, showLives: true, icon: '🗑️', render: (api) => <BinShotGame api={api} /> },
  { id: 'paperglider', category: 'school', free: false, icon: '✈️', render: (api) => <PaperGliderGame api={api} /> },
  { id: 'dotsboxes', category: 'school', free: false, icon: '🔲', render: (api) => <DotsBoxesGame api={api} /> },
  { id: 'eraserflick', category: 'school', free: false, icon: '🏫', render: (api) => <EraserFlickGame api={api} /> },
  { id: 'mathsprint', category: 'school', free: false, showLives: true, icon: '🧮', render: (api) => <MathSprintGame api={api} /> },
  // Brain
  { id: 'memorymatch', category: 'brain', free: true, icon: '🃏', render: (api) => <MemoryMatchGame api={api} /> },
  { id: 'cratepush', category: 'brain', free: false, icon: '📦', render: (api) => <CratePushGame api={api} /> },
  { id: 'tilefusion', category: 'brain', free: false, icon: '🔢', render: (api) => <TileFusionGame api={api} /> },
  { id: 'pixellogic', category: 'brain', free: false, showLives: true, icon: '🧩', render: (api) => <PixelLogicGame api={api} /> },
  { id: 'blockdrop', category: 'brain', free: false, icon: '🟪', render: (api) => <BlockDropGame api={api} /> },
  { id: 'fourstack', category: 'brain', free: false, icon: '🔴', render: (api) => <FourStackGame api={api} /> },
];

export const GAMES: GameDef[] = DEFS.map((def) => ({ ...def, art: ART[def.id] }));

export const CATEGORIES: Category[] = ['classics', 'action', 'arcade', 'school', 'brain'];

export function gameById(id: string): GameDef | undefined {
  return GAMES.find((g) => g.id === id);
}

export function gameColor(game: GameDef): string {
  return categoryColors[game.category];
}
