/**
 * In-game actor sprites (transparent PNGs from scripts/gen-actor-sprites.mjs).
 * Rendered with <Image> at game scale — generated 16× so downscaling stays
 * crisp. Add a sprite: draw the map in the script, rerun it, register here.
 */
export const ACTORS = {
  frog: require('../../../assets/actors/frog.png'),
  car_side_yellow: require('../../../assets/actors/car_side_yellow.png'),
  car_side_cyan: require('../../../assets/actors/car_side_cyan.png'),
  car_side_magenta: require('../../../assets/actors/car_side_magenta.png'),
  car_side_orange: require('../../../assets/actors/car_side_orange.png'),
  car_side_red: require('../../../assets/actors/car_side_red.png'),
  truck_side_yellow: require('../../../assets/actors/truck_side_yellow.png'),
  truck_side_magenta: require('../../../assets/actors/truck_side_magenta.png'),
  truck_side_red: require('../../../assets/actors/truck_side_red.png'),
  racecar_cyan: require('../../../assets/actors/racecar_cyan.png'),
  racecar_red: require('../../../assets/actors/racecar_red.png'),
  racecar_yellow: require('../../../assets/actors/racecar_yellow.png'),
  racecar_magenta: require('../../../assets/actors/racecar_magenta.png'),
  racecar_orange: require('../../../assets/actors/racecar_orange.png'),
  player_racer: require('../../../assets/actors/player_racer.png'),
  taxi_top: require('../../../assets/actors/taxi_top.png'),
  suv_top: require('../../../assets/actors/suv_top.png'),
  pickup_top: require('../../../assets/actors/pickup_top.png'),
  bus_top: require('../../../assets/actors/bus_top.png'),
  sedan_top_magenta: require('../../../assets/actors/sedan_top_magenta.png'),
  sedan_top_white: require('../../../assets/actors/sedan_top_white.png'),
  pine_tree: require('../../../assets/actors/pine_tree.png'),
  road_sign_blue: require('../../../assets/actors/road_sign_blue.png'),
  explosion_burst: require('../../../assets/actors/explosion_burst.png'),
  duck_a: require('../../../assets/actors/duck_a.png'),
  duck_b: require('../../../assets/actors/duck_b.png'),
  duck_fall: require('../../../assets/actors/duck_fall.png'),
  dog_sniff: require('../../../assets/actors/dog_sniff.png'),
  dog_duck: require('../../../assets/actors/dog_duck.png'),
  dog_laugh: require('../../../assets/actors/dog_laugh.png'),
  leaf_tree: require('../../../assets/actors/leaf_tree.png'),
  island_kid_a: require('../../../assets/actors/island_kid_a.png'),
  island_kid_b: require('../../../assets/actors/island_kid_b.png'),
  snail_bug: require('../../../assets/actors/snail_bug.png'),
  cobra: require('../../../assets/actors/cobra.png'),
  axe_gold: require('../../../assets/actors/axe_gold.png'),
  banana: require('../../../assets/actors/banana.png'),
  rock_red: require('../../../assets/actors/rock_red.png'),
  hunt_tree: require('../../../assets/actors/hunt_tree.png'),
  tall_grass: require('../../../assets/actors/tall_grass.png'),
  jungle_trunk: require('../../../assets/actors/jungle_trunk.png'),
  soil_block: require('../../../assets/actors/soil_block.png'),
  heart_red: require('../../../assets/actors/heart_red.png'),
  cloud_puff: require('../../../assets/actors/cloud_puff.png'),
  bush_round: require('../../../assets/actors/bush_round.png'),
  canopy: require('../../../assets/actors/canopy.png'),
  grass_tuft: require('../../../assets/actors/grass_tuft.png'),
  flower_red: require('../../../assets/actors/flower_red.png'),
  lander: require('../../../assets/actors/lander.png'),
  hen: require('../../../assets/actors/hen.png'),
  egg: require('../../../assets/actors/egg.png'),
  basket: require('../../../assets/actors/basket.png'),
  pin: require('../../../assets/actors/pin.png'),
  invader_magenta: require('../../../assets/actors/invader_magenta.png'),
  invader_cyan: require('../../../assets/actors/invader_cyan.png'),
  cannon: require('../../../assets/actors/cannon.png'),
  ship_mk2: require('../../../assets/actors/ship_mk2.png'),
  ship_mk3: require('../../../assets/actors/ship_mk3.png'),
  boss_saucer: require('../../../assets/actors/boss_saucer.png'),
  tank_green: require('../../../assets/actors/tank_green.png'),
  tank_red: require('../../../assets/actors/tank_red.png'),
  climber: require('../../../assets/actors/climber.png'),
  ape: require('../../../assets/actors/ape.png'),
  chopper: require('../../../assets/actors/chopper.png'),
  hunter: require('../../../assets/actors/hunter.png'),
  mummy: require('../../../assets/actors/mummy.png'),
  rocket: require('../../../assets/actors/rocket.png'),
  meteor: require('../../../assets/actors/meteor.png'),
  bird: require('../../../assets/actors/bird.png'),
  miner: require('../../../assets/actors/miner.png'),
  gemstone: require('../../../assets/actors/gemstone.png'),
  plane_enemy: require('../../../assets/actors/plane_enemy.png'),
  hopper: require('../../../assets/actors/hopper.png'),
  buggy: require('../../../assets/actors/buggy.png'),
  ghost_magenta: require('../../../assets/actors/ghost_magenta.png'),
  ghost_cyan: require('../../../assets/actors/ghost_cyan.png'),
  pumpkin: require('../../../assets/actors/pumpkin.png'),
  zombie: require('../../../assets/actors/zombie.png'),
  bat: require('../../../assets/actors/bat.png'),
  crawler_head: require('../../../assets/actors/crawler_head.png'),
  mushroom: require('../../../assets/actors/mushroom.png'),
} as const;

export type ActorName = keyof typeof ACTORS;
